import type { Court } from './types';

export const courts: Court[] = [
  {
    id: '1',
    name: 'Sunset Pickleball Club',
    rating: 4.8,
    pricePerHour: 500,
    tags: ['outdoor', 'lights'],
    sport: 'Pickleball',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/pickle1/600/400',
    imageHint: 'pickleball court',
    address: '1234 Sunset Blvd, San Francisco',
    description: 'Premier outdoor pickleball facility with 8 championship courts. Evening play available under LED lights.',
    amenities: ['PRO SHOP', 'LOCKER ROOM', 'CAFE', 'OUTDOOR', 'HARD COURT'],
    operatingHours: '6:00 AM - 10:00 PM',
    cost: 'Paid',
    surface: 'Hard Court',
    rules: ['No food or drinks on court.'],
    reviewsCount: 124,
  },
  {
    id: '2',
    name: 'Downtown Hoops Center',
    rating: 4.9,
    pricePerHour: 750,
    tags: ['indoor'],
    sport: 'Basketball',
    type: 'Indoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/basket2/600/400',
    imageHint: 'indoor basketball',
    address: '5678 Downtown Ave, San Francisco',
    description: 'State-of-the-art indoor basketball facility.',
    amenities: ['LOCKER ROOM', 'SHOWERS'],
    operatingHours: '8:00 AM - 11:00 PM',
    cost: 'Paid',
    surface: 'Hardwood',
    rules: [],
    reviewsCount: 230,
  },
  {
    id: '3',
    name: 'Greenwood Tennis Club',
    rating: 4.7,
    pricePerHour: 1200,
    tags: ['outdoor', 'lights'],
    sport: 'Tennis',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/tennis1/600/400',
    imageHint: 'tennis court',
    address: '910 Greenwood Park, San Francisco',
    description: 'Beautifully maintained clay tennis courts.',
    amenities: ['PRO SHOP', 'CAFE'],
    operatingHours: '7:00 AM - 9:00 PM',
    cost: 'Paid',
    surface: 'Clay',
    rules: [],
    reviewsCount: 98,
  },
  {
    id: '4',
    name: 'Community Rec Center',
    rating: 4.5,
    pricePerHour: 0,
    tags: ['outdoor'],
    sport: 'Basketball',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/basket1/600/400',
    imageHint: 'basketball court',
    address: '111 Community Dr, San Francisco',
    description: 'Free public basketball courts.',
    amenities: ['WATER FOUNTAIN'],
    operatingHours: '24 Hours',
    cost: 'Free',
    surface: 'Asphalt',
    rules: [],
    reviewsCount: 45,
  },
  {
    id: '5',
    name: 'The Pickleball Dome',
    rating: 4.9,
    pricePerHour: 600,
    tags: ['indoor', 'lights'],
    sport: 'Pickleball',
    type: 'Indoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/pickle2/600/400',
    imageHint: 'indoor pickleball',
    address: '222 Dome Rd, San Francisco',
    description: 'Indoor pickleball for year-round play.',
    amenities: ['LOCKER ROOM', 'CAFE'],
    operatingHours: '9:00 AM - 10:00 PM',
    cost: 'Paid',
    surface: 'Hard Court',
    rules: [],
    reviewsCount: 180,
  },
  {
    id: '6',
    name: 'Grand Slam Tennis Arena',
    rating: 4.8,
    pricePerHour: 1500,
    tags: ['outdoor', 'lights'],
    sport: 'Tennis',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/tennis2/600/400',
    imageHint: 'tennis night',
    address: '333 Grand Slam Way, San Francisco',
    description: 'Professional quality tennis courts.',
    amenities: ['PRO SHOP', 'LOCKER ROOM', 'SHOWERS'],
    operatingHours: '6:00 AM - 12:00 AM',
    cost: 'Paid',
    surface: 'Hard Court',
    rules: [],
    reviewsCount: 310,
  },
];
