import type { Court } from './types';

export const courts: Court[] = [
  {
    id: '1',
    name: 'Sunset Pickleball Club',
    rating: 4.8,
    pricePerHour: 500,
    tags: ['outdoor', 'lights'],
    sport: 'Pickleball',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/pickle1/600/400',
    imageHint: 'pickleball court',
  },
  {
    id: '2',
    name: 'Downtown Hoops Center',
    rating: 4.9,
    pricePerHour: 750,
    tags: ['indoor'],
    sport: 'Basketball',
    type: 'Indoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/basket2/600/400',
    imageHint: 'indoor basketball',
  },
  {
    id: '3',
    name: 'Greenwood Tennis Club',
    rating: 4.7,
    pricePerHour: 1200,
    tags: ['outdoor', 'lights'],
    sport: 'Tennis',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/tennis1/600/400',
    imageHint: 'tennis court',
  },
  {
    id: '4',
    name: 'Community Rec Center',
    rating: 4.5,
    pricePerHour: 0,
    tags: ['outdoor'],
    sport: 'Basketball',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/basket1/600/400',
    imageHint: 'basketball court',
  },
  {
    id: '5',
    name: 'The Pickleball Dome',
    rating: 4.9,
    pricePerHour: 600,
    tags: ['indoor', 'lights'],
    sport: 'Pickleball',
    type: 'Indoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/pickle2/600/400',
    imageHint: 'indoor pickleball',
  },
  {
    id: '6',
    name: 'Grand Slam Tennis Arena',
    rating: 4.8,
    pricePerHour: 1500,
    tags: ['outdoor', 'lights'],
    sport: 'Tennis',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/tennis2/600/400',
    imageHint: 'tennis night',
  },
];
