import type { Court, CourtAvailability } from './types';

export const courts: Court[] = [
  {
    id: '1',
    name: 'Silliman University Courts',
    rating: 4.8,
    pricePerHour: 500,
    tags: ['outdoor', 'lights'],
    sport: 'Pickleball',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/pickle1/600/400',
    imageHint: 'pickleball court',
    address: 'Silliman Ave, Dumaguete City',
    description:
      'Premier outdoor pickleball facility with 8 championship courts. Evening play available under LED lights.',
    amenities: [{ name: 'PRO SHOP' }, { name: 'LOCKER ROOM' }, { name: 'CAFE' }],
    operatingHours: '6:00 AM - 10:00 PM',
    cost: 'Paid',
    surface: 'Hard Court',
    rules: ['No food or drinks on court.'],
    reviewsCount: 124,
    lat: 9.313,
    lng: 123.306,
    sportTypes: ['Pickleball', 'Tennis'],
    openTime: '06:00',
    closeTime: '22:00',
    heroImageUrl: 'https://picsum.photos/seed/pickle-detail/1200/400',
  },
  {
    id: '2',
    name: 'Foundation University Gym',
    rating: 4.9,
    pricePerHour: 750,
    tags: ['indoor'],
    sport: 'Basketball',
    type: 'Indoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/basket2/600/400',
    imageHint: 'indoor basketball',
    address: 'Dr. V. Locsin St, Dumaguete City',
    description: 'State-of-the-art indoor basketball facility.',
    amenities: [{ name: 'LOCKER ROOM' }, { name: 'SHOWERS' }],
    operatingHours: '8:00 AM - 11:00 PM',
    cost: 'Paid',
    surface: 'Hardwood',
    rules: [],
    reviewsCount: 230,
    lat: 9.317,
    lng: 123.303,
    sportTypes: ['Basketball'],
    openTime: '08:00',
    closeTime: '23:00',
    heroImageUrl: 'https://picsum.photos/seed/basket-detail/1200/400',
  },
  {
    id: '3',
    name: 'Praxevilla Tennis Courts',
    rating: 4.7,
    pricePerHour: 1200,
    tags: ['outdoor', 'lights'],
    sport: 'Tennis',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/tennis1/600/400',
    imageHint: 'tennis court',
    address: 'Praxevilla, Rovira Rd, Dumaguete City',
    description: 'Beautifully maintained clay tennis courts.',
    amenities: [{ name: 'PRO SHOP' }, { name: 'CAFE' }],
    operatingHours: '7:00 AM - 9:00 PM',
    cost: 'Paid',
    surface: 'Clay',
    rules: [],
    reviewsCount: 98,
    lat: 9.296,
    lng: 123.295,
    sportTypes: ['Tennis'],
    openTime: '07:00',
    closeTime: '21:00',
    heroImageUrl: 'https://picsum.photos/seed/tennis-detail/1200/400',
  },
  {
    id: '4',
    name: 'Rizal Boulevard Court',
    rating: 4.5,
    pricePerHour: 0,
    tags: ['outdoor'],
    sport: 'Basketball',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/basket1/600/400',
    imageHint: 'basketball court',
    address: 'Rizal Boulevard, Dumaguete City',
    description: 'Free public basketball courts with a sea view.',
    amenities: [{ name: 'WATER FOUNTAIN' }],
    operatingHours: '24 Hours',
    cost: 'Free',
    surface: 'Asphalt',
    rules: [],
    reviewsCount: 45,
    lat: 9.308,
    lng: 123.31,
    sportTypes: ['Basketball', 'Futsal'],
    openTime: '00:00',
    closeTime: '24:00',
    heroImageUrl: 'https://picsum.photos/seed/community-detail/1200/400',
  },
  {
    id: '5',
    name: 'The Pickleball Dome Dgte',
    rating: 4.9,
    pricePerHour: 600,
    tags: ['indoor', 'lights'],
    sport: 'Pickleball',
    type: 'Indoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/pickle2/600/400',
    imageHint: 'indoor pickleball',
    address: 'Bacong-Valencia Rd, Dumaguete City',
    description: 'Indoor pickleball for year-round play.',
    amenities: [{ name: 'LOCKER ROOM' }, { name: 'CAFE' }],
    operatingHours: '9:00 AM - 10:00 PM',
    cost: 'Paid',
    surface: 'Hard Court',
    rules: [],
    reviewsCount: 180,
    lat: 9.28,
    lng: 123.28,
    sportTypes: ['Pickleball'],
    openTime: '09:00',
    closeTime: '22:00',
    heroImageUrl: 'https://picsum.photos/seed/dome-detail/1200/400',
  },
  {
    id: '6',
    name: 'LPGA Tennis Club',
    rating: 4.8,
    pricePerHour: 1500,
    tags: ['outdoor', 'lights'],
    sport: 'Tennis',
    type: 'Outdoor',
    isLiveAvailable: true,
    imageUrl: 'https://picsum.photos/seed/tennis2/600/400',
    imageHint: 'tennis night',
    address: 'E J. Blanco Dr, Dumaguete City',
    description: 'Professional quality tennis courts.',
    amenities: [{ name: 'PRO SHOP' }, { name: 'LOCKER ROOM' }, { name: 'SHOWERS' }],
    operatingHours: '6:00 AM - 12:00 AM',
    cost: 'Paid',
    surface: 'Hard Court',
    rules: [],
    reviewsCount: 310,
    lat: 9.298,
    lng: 123.313,
    sportTypes: ['Tennis'],
    openTime: '06:00',
    closeTime: '24:00',
    heroImageUrl: 'https://picsum.photos/seed/grandslam-detail/1200/400',
  },
];


export const courtAvailability: CourtAvailability = {
  '2026-01-05': {
    unavailableTimes: ['14:00', '16:00', '21:00'],
  },
  '2026-01-06': {
    unavailableTimes: ['09:00', '10:00', '15:00', '18:00'],
  },
  '2026-01-07': {
    unavailableTimes: ['08:00', '11:00', '12:00', '13:00', '17:00'],
  },
};

    