export type Court = {
  id: string;
  name: string;
  rating: number;
  pricePerHour?: number;
  tags: ('outdoor' | 'indoor' | 'lights')[];
  sport: 'Pickleball' | 'Basketball' | 'Tennis' | 'Badminton' | 'Volleyball' | 'Futsal';
  type: 'Indoor' | 'Outdoor';
  isLiveAvailable: boolean;
  imageUrl: string;
  imageHint: string;
  address: string;
  description: string;
  amenities: string[];
  operatingHours: string;
  cost: 'Free' | 'Paid';
  surface: string;
  rules: string[];
  reviewsCount: number;
};
